#VGGSound:
  #video_path: /home/hdd/sophie/data/mmaudio_test_sample/vgg_samples
  #csv_path: /home/hdd/sophie/data/mmaudio_test_sample/vgg_samples.csv

  #video_path: /home/sophie/repos/AVS/data_pipeline_scripts/test_label_detectors/only_mp4/sav_011
  #csv_path: /home/sophie/repos/AVS/data_pipeline_scripts/test_label_detectors/only_mp4/blip2_27b_captions.csv

  #video_path: /home/sophie/repos/AVS/data_pipeline_scripts/test_label_detectors_blacked_out_mp4/sav_011_duration
  #csv_path: /home/sophie/repos/AVS/data_pipeline_scripts/test_label_detectors_blacked_out_mp4/blacked_out_blip2_27b_captions.csv

  # blacked out captions but original video
  #video_path: /home/sophie/repos/AVS/data_pipeline_scripts/test_label_detectors/only_mp4/sav_011
  #csv_path: /home/sophie/repos/AVS/data_pipeline_scripts/test_label_detectors_blacked_out_mp4/blacked_out_blip2_27b_captions.csv

SAVDataset:
  # duration in filenames not in csv
  video_path: /home/sophie/repos/AVS/data_pipeline_scripts/test_1507
  #csv_path: /home/sophie/repos/AVS/data_pipeline_scripts/test_1407/labels.csv
  csv_path: /home/sophie/repos/AVS/data_pipeline_scripts/test_1507/florence_base_captions.csv